import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "./components/layout/header";
import Footer from "./components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fetroshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className,
          " bg-light dark:bg-dark max-w-screen w-full h-screen")
        }
      >
        <div className="fixed z-50 top-0 w-full">
          <Headers />
        </div>
        <main className="flex min-h-screen flex-col items-center justify-between px-10 pt-28 2xl:p-28">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
