import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../styles/globals.css";
import HeaderDownload from "./components/layouts/header";
import FooterDownload from "./components/layouts/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fetroshop",
  description: "Generated by create next app",
};

export default function DownloadLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "bg-light dark:bg-dark")}>
        <div className="w-full md:w-[500px] lg:w-full 2xl:w-3/4 mx-auto">
          <HeaderDownload />
          <main className="flex min-h-[60vh] flex-col items-center justify-center">
            {children}
          </main>
          <FooterDownload />
        </div>
      </body>
    </html>
  );
}
