export const dataBrands = [
    'A',
    'A&W',
    'A-SYIFA',
    'A.T.B',
    'AA',
    'AAA',
    'AB',
    'ABC',
    'ABC Battery',
    'ABC Tulus Mix',
    'Abe Food',
    'ABSTRACT',
    'Acaiberry ABC',
    'acaraki',
    'ACCESS',
    'Acnes',
    'ACNOL',
    'Actifed',
    'ACTIMED',
    'Activ Water',
    'Adem Sari',
    'ades',
    'ADILA Snack',
    'Adinata',
    'Adjie',
    'Agarasa',
    'AGS',
    'Agung Sari',
    'B&B',
    'B&B Kids',
    'Baa..guss',
    'BaBe',
    'baby Dove',
    'Baby Happy',
    'baby HUKI',
    'Bachoc',
    'BAGORLIYA',
    'Bagus',
    'BAGUS SNACK',
    'Bahari Food',
    'BAKE!',
    'BAKED',
    'BakedID Food',
    'Bakmi Mewah',
    'Bambi Baby',
    'bamboe',
    'BANACHIPS',
    'BANAFAM',
    'BANANA BOAT',
    'Bananania',
    'BANGO',
    'Banyuatis',
    'Barbie',
    'Barco',
    'Barilla',
    'BATANG COFFEE',
    'BAYCLIN',
    'BayFresh',
    'Baygon'
];
